### ISSUE TITLE
case sensitivity

### ISSUE THREAD

**Issue by ddeepwell** [bastorer/SPINSpy#7]
Remove case sensitivity

**Comment by bastorer** [comment]
We can do this very easily if we're willing to be completely case insensitive (we basically cast everything to lower case in get_params).

**Comment by ddeepwell** [comment]
I think things like Nx and Lx (same for y and z) should remain upper case (in first letter) for the param object formed from the get_params function. The get_params function should just look for NX or nx or any combination of those in upper and lower case and pass it into Nx (same for Lx). Could we just do an if statement (4 times for the 4 options) for just the number of points in each dimension and the length of each dimension? These (and maybe some others?) we should standardize, but user specific parameters we should leave as the user sets them in the spins.conf file.

David

**Comment by bastorer** [comment]
Yeah, leaving user parameters as they are would be good. We can hard-code the possible options for N_, L_, and any others that come up easily enough.
